# Generated by Django 6.0.2 on 2026-02-21 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], default='Unmarried', max_length=20)),
                ('aadhar', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('identification_mark', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField()),
                ('correspondence_address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('education_json', models.JSONField(default=list)),
                ('documents', models.JSONField(default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
