# Generated by Django 6.0.2 on 2026-02-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permanent_address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='Chhattisgarh', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('aadhar', models.CharField(blank=True, max_length=20)),
                ('samagra_id', models.CharField(blank=True, max_length=20)),
                ('caste_cert_no', models.CharField(blank=True, max_length=50)),
                ('income_cert_no', models.CharField(blank=True, max_length=50)),
                ('tenth_board', models.CharField(blank=True, max_length=100)),
                ('tenth_result', models.CharField(blank=True, max_length=50)),
                ('twelfth_board', models.CharField(blank=True, max_length=100)),
                ('twelfth_result', models.CharField(blank=True, max_length=50)),
                ('graduation', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
