# Generated by Django 6.0.2 on 2026-02-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delete_studentprofile'),
    ]

    operations = [
    ]
