# Generated by Django 6.0.2 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_aadhaar_linked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_extra_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_extra_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
