# Generated by Django 6.0.2 on 2026-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_academic_extra_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_extra_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_extra_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_extra_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
