# Generated by Django 6.0.2 on 2026-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vacancy_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['display_order', 'last_date', 'id']},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('government', 'Government'), ('student', 'Student')], default='government', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='icon_name',
            field=models.CharField(blank=True, default='description', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancy_images/'),
        ),
    ]
