# Generated by Django 6.0.2 on 2026-02-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_vacancy_options_vacancy_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_admin", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="chat_attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_messages", to="accounts.userprofile")),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
