# Generated by Django 6.0.2 on 2026-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_graduation_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
        migrations.AlterField(
            model_name='masterdatafield',
            name='step',
            field=models.CharField(choices=[('personal', 'Personal'), ('address', 'Address'), ('academic', 'Academic'), ('college', 'College'), ('bank', 'Bank'), ('subject', 'Subject'), ('documents', 'Documents')], default='personal', max_length=20),
        ),
    ]
