# Generated by Django 6.0.2 on 2026-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_userprofile_avatar_alter_masterdatafield_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='mobile_page_size',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
