# Generated by Django 6.0.2 on 2026-05-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_vacancy_mobile_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='original_name',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_documents/'),
        ),
    ]
